---
Name: schema
---
Page:
  # default_image: 'path/to/logo.png'
  extensions:
    - 'Broarm\Schema\SchemaExtension'
  active_schema:
    local_business: 'Broarm\Schema\Builder\LocalBusiness'
    website: 'Broarm\Schema\Builder\Website'
    breadcrumbs: 'Broarm\Schema\Builder\Breadcrumbs'

SilverStripe\Blog\Model\BlogPost:
  active_schema:
    newsArticle: 'Broarm\Schema\Builder\NewsArticle'
