---
Name: schema
---
Page:
  # default_image: 'path/to/logo.png'
  extensions:
    - 'Broarm\Schema\SchemaExtension'
  active_schema:
    - 'Broarm\Schema\Builders\Website'
    - 'Broarm\Schema\Builders\Breadcrumbs'
# SilverStripe\Blog\Model\BlogPost:
#   active_schema:
#     - 'Broarm\Schema\Builder\NewsArticle'
# Broarm\Schema\ComposerCleanup\SpatieCleanup:
#   keep_files:
#     - 'path/to/file'
