---
Name: schema
---
Page:
  # default_image: 'path/to/logo.png'
  extensions:
    - 'Broarm\Schema\SchemaExtension'
  active_schema:
    - 'Broarm\Schema\Builder\Website'
    - 'Broarm\Schema\Builder\Breadcrumbs'
# SilverStripe\Blog\Model\BlogPost:
#   active_schema:
#     - 'Broarm\Schema\Builder\NewsArticle'
